# Generated by Django 3.2.7 on 2021-10-31 16:09

from django.db import migrations, models
import django.db.models.deletion
import idiokeDaily.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_language', models.PositiveSmallIntegerField(choices=[(0, 'English'), (1, 'Spanish')], default=0)),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Basics I'), (1, 'Basics II'), (2, 'Intermediate')], default=0)),
                ('dayNumber', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Daily Events',
                'ordering': ['level', 'dayNumber'],
            },
        ),
        migrations.CreateModel(
            name='TongueTwister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_language', models.PositiveSmallIntegerField(choices=[(0, 'English'), (1, 'Spanish')], default=0)),
                ('audio', models.FileField(blank=True, null=True, upload_to=idiokeDaily.models.music_full_audio_file)),
                ('shortname', models.CharField(blank=True, max_length=64, null=True)),
                ('tl_text', models.TextField(blank=True, null=True)),
                ('phonetic_text', models.TextField(blank=True, null=True)),
                ('text_trans', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Tongue Twisters',
                'ordering': ['target_language', 'published', 'shortname'],
            },
        ),
        migrations.CreateModel(
            name='DailyLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(blank=True, max_length=64, null=True)),
                ('lessonEnglish', models.TextField(blank=True, null=True)),
                ('lyrics_trans', models.TextField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('dayNumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_event', to='idiokeDaily.dailyevent')),
            ],
            options={
                'verbose_name_plural': 'Daily Lessons',
                'ordering': ['published', 'shortname'],
            },
        ),
    ]
